// All user-facing copy for the admin portal lives here (see REQUIREMENTS.md:
// central text file, English only, no emoji).
export const text = {
  appName: "Business of Happiness Admin",
  common: {
    loading: "Loading",
    unknownUser: "Unknown user",
    supabaseErrorPrefix: "Supabase error:",
    somethingWentWrong: "Something went wrong.",
    uploading: "Uploading...",
    save: "Save",
    delete: "Delete",
    cancel: "Cancel",
    noData: "Supabase returned no data.",
  },
  signIn: {
    title: "Business of Happiness Admin",
    subtitle: "Sign in with your admin account to continue.",
    googleButton: "Sign in with Google",
    adminsOnly: "This portal is for admins only.",
  },
  nav: {
    inbox: "Inbox",
    content: "Content",
    whitelist: "Whitelist",
    announcements: "Announcements",
    moderation: "Moderation",
    signOut: "Sign out",
  },
  placeholder: {
    comingSoon: "This section is coming soon.",
  },
  inbox: {
    title: "Tarryn Inbox",
    subtitle: "Read and reply to Reach Out Here direct messages.",
    loading: "Loading inbox",
    loadError: "Inbox could not be loaded",
    emptyTitle: "No conversations yet",
    emptyBody: "Messages sent to Tarryn by app users will appear here.",
    unread: "Unread",
    latestInbound: "Latest message from user",
    latestOutbound: "Latest reply from staff",
    sessionRequired: "You must be signed in to reply.",
    tarrynAccountMissing:
      "No Tarryn account was found. Replies cannot be sent until a user with the Tarryn role exists.",
  },
  conversation: {
    emptyTitle: "Select a conversation",
    emptyBody: "Choose a user from the inbox to view their full message history.",
    replyLabel: "Reply message",
    replyPlaceholder: "Write a reply to send as Tarryn",
    sentByPrefix: "Sent by",
    send: "Send reply",
    sending: "Sending",
    mutationError: "Reply could not be sent",
  },
  announcements: {
    title: "Announcements",
    subtitle: "Publish app-wide updates or course-specific notices for students.",
    composeTitle: "Compose announcement",
    scopeLabel: "Audience",
    appWideOption: "App-wide",
    bodyLabel: "Message",
    bodyPlaceholder: "Write the announcement students should see.",
    publish: "Publish announcement",
    publishing: "Publishing",
    existingTitle: "Existing announcements",
    loading: "Loading announcements",
    empty: "No announcements have been published yet.",
    deleting: "Deleting",
    confirmDelete: "Delete this announcement? This cannot be undone.",
    loadError: "Could not load announcements. Please try again.",
    bodyRequired: "Write an announcement before publishing.",
    sessionRequired: "Your admin session could not be verified. Please sign in again.",
    unknownCourse: "Unknown course",
    createdPrefix: "Published",
  },
  whitelist: {
    title: "Whitelist",
    subtitle: "Manage course access by adding existing user accounts to each course.",
    courseLabel: "Course",
    loading: "Loading whitelist",
    loadError: "Could not load whitelist data. Please try again.",
    emptyCourses: "Create a course before adding users to a whitelist.",
    emptyUsers: "No users have access to this course yet.",
    addTitle: "Add user access",
    emailLabel: "User email",
    emailPlaceholder: "student@example.com",
    add: "Add to whitelist",
    adding: "Adding",
    remove: "Remove",
    removing: "Removing",
    emailRequired: "Enter an email address before adding a user.",
    userNotFound: "No user account matches that email. The account must exist first.",
    courseRequired: "Choose a course before adding a user.",
    confirmRemove: "Remove this user from the course whitelist?",
    accessSince: "Access since",
    userCountCaption: (count: number, startDate: string | null) =>
      `${count} ${count === 1 ? "user" : "users"} whitelisted${startDate ? ` for the ${startDate} start date` : ""}.`,
  },
  moderation: {
    title: "Moderation",
    description: "Browse community posts and replies across the global feed and course feeds.",
    feedLabel: "Feed",
    globalFeed: "Business of Happiness global feed",
    loading: "Loading community feed...",
    empty: "No posts in this feed yet.",
    unknownAuthor: "Unknown member",
    noBody: "No text content",
    media: "Media",
    replies: "Replies",
    noReplies: "No replies yet.",
    deletePost: "Delete post",
    deleteReply: "Delete reply",
    confirmTitle: "Confirm deletion",
    confirmPost: "Delete this post and all of its replies? This cannot be undone.",
    confirmReply: "Delete this reply? This cannot be undone.",
    cancel: "Cancel",
    confirm: "Confirm delete",
    deleting: "Deleting...",
    loadError: "Unable to load moderation content.",
    deleteError: "Unable to delete content.",
    selectedCourse: "Selected course",
  },
  content: {
    title: "Content Management",
    subtitle: "Manage courses, sections, lessons, videos, PDFs, and audio resources.",
    loading: "Loading content...",
    emptyCourses: "Create a course to start adding sections and lessons.",
    saveError: "The content update could not be saved.",
    coursesHeading: "Courses",
    courseTitle: "Course title",
    startDate: "Start date",
    addCourse: "Add course",
    noStartDate: "No start date",
    sectionsHeading: "Sections",
    emptySections: "No sections yet. Add one to start building this course.",
    fieldTitle: "Title",
    fieldType: "Type",
    moduleGoLive: "Module go-live",
    addSection: "Add section",
    editCourse: "Edit course",
    deleteCourse: "Delete course",
    saveCourse: "Save course",
    saveSection: "Save section",
    lessonsHeading: "Lessons",
    emptyLessons: "No lessons in this section yet.",
    fieldVideo: "Video",
    fieldFile: "File",
    uploadVideo: "Upload video",
    addLesson: "Add lesson",
    saveLesson: "Save lesson",
    videoAttached: "Video attached",
    noVideo: "No video yet",
    resourcesHeading: "Resources",
    emptyResources: "No resources attached to this lesson.",
    uploadFile: "Upload file",
    addResource: "Add resource",
    pasteUrlInstead: "Paste a URL instead",
    uploadFileInstead: "Upload a file instead",
    urlPlaceholder: "https://",
    replaceAction: "Replace",
    removeFile: "Remove file",
    goLivePrefix: "Go-live",
    lessonCount: (count: number) => (count === 1 ? "1 lesson" : `${count} lessons`),
    resourceCount: (count: number) => (count === 1 ? "1 resource" : `${count} resources`),
    confirmDeleteCourse: (title: string) =>
      `Delete ${title}? This also deletes its sections and lessons.`,
    confirmDeleteSection: (title: string) =>
      `Delete section ${title}? Its lessons will also be deleted.`,
    confirmDeleteLesson: (title: string) =>
      `Delete lesson ${title}? Its resources will also be deleted.`,
    confirmDeleteResource: (title: string) => `Delete resource ${title}?`,
  },
} as const;
